# Generated by Django 5.2.6 on 2025-11-20 13:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fur_shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genres',
            },
        ),
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('access_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Eyes_color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heterochromia', models.BooleanField()),
                ('left_eye_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='left_eye_usages', to='core.color')),
                ('right_eye_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='right_eye_usages', to='core.color')),
            ],
            options={
                'ordering': ('right_eye_color', 'left_eye_color'),
            },
        ),
        migrations.CreateModel(
            name='Fur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fur_styles_usages', to='core.color')),
                ('secondary_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fur_syles_usages', to='core.color')),
                ('shape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fur_shape')),
                ('pattern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pattern')),
            ],
            options={
                'ordering': ('shape', 'primary_color', 'secondary_color', 'pattern'),
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('eyes_color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.eyes_color')),
                ('fur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fur')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('age', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(99)])),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=4)),
                ('annotations', models.CharField(blank=True, max_length=1000, null=True)),
                ('breed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.breed')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.gender')),
            ],
            options={
                'ordering': ('name', 'breed', '-entry_date'),
            },
        ),
        migrations.AddConstraint(
            model_name='eyes_color',
            constraint=models.UniqueConstraint(fields=('right_eye_color', 'left_eye_color'), name='unique_eye_color_pair'),
        ),
        migrations.AddConstraint(
            model_name='breed',
            constraint=models.UniqueConstraint(fields=('name', 'fur', 'eyes_color'), name='unique_race_characteristics'),
        ),
        migrations.AddConstraint(
            model_name='fur',
            constraint=models.UniqueConstraint(fields=('shape', 'primary_color', 'secondary_color', 'pattern'), name='unique_fur_style'),
        ),
    ]
